version: '3.5'
services:
  reti-server:
    build: .
    restart: always
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - .:/code
    environment:
      - PORT=8000
      - HOST=0.0.0.0